"""
ME 144/244: Modeling, Simulation, and Digital Twins of Drone-Based Systems
Project 7: Aerial Firefighting
Spring 2026 Semester

"""
import numpy as np
import pickle
"""
This script writes the parameters to a dictionary in a pickle file that can be read in during the simulation.
Separating from full sim makes things cleaner.
"""

# --- Constants ---
GX = 0                               # m / s^2
GY = -9.81                           # m / s^2
GZ = 0                               # m / s^2
DT = 0.05                            # s
STEPS = 1200                         # 60 s
FRACTION_PARTICLES_TRACKED = 1e-6

# --- Fire Zone (Box) ---
FIRE_X_MIN, FIRE_X_MAX = 200, 300
FIRE_Z_MIN, FIRE_Z_MAX = -50, 50

# --- Fire Zone Shape ---
# Set to 'box' to use FIRE_X/Z_MIN/MAX, or 'circle' for a circular zone.
FIRE_ZONE_SHAPE = 'box'              # 'box' or 'circle'
FIRE_CENTER_X   = (FIRE_X_MIN + FIRE_X_MAX) / 2   # centre x for circle (m)
FIRE_CENTER_Z   = (FIRE_Z_MIN + FIRE_Z_MAX) / 2   # centre z for circle (m)
FIRE_RADIUS     = max(FIRE_X_MAX - FIRE_X_MIN,
                      FIRE_Z_MAX - FIRE_Z_MIN) / 2  # radius for circle (m)

# Updraft
# Peak updraft speed at ground level and exponential height decay constant.
UPDRAFT_VELOCITY = 10.0              # peak updraft speed at ground level [m/s]
UPDRAFT_DECAY    = 0.02              # exponential height decay constant [1/m]
                                     # at y=100 m: 20*exp(-2) ≈ 2.7 m/s  (< gravity)
                                     # at y= 50 m: 20*exp(-1) ≈ 7.4 m/s

# Nozzle
NOZZLE_AFT_OFFSET   = 5.0           # distance aft of CG to sprayer base [m]
NOZZLE_DROP_OFFSET  = 2.0           # vertical drop from sprayer base to end (m)

# --- Simulation Limits ---
Y0_MAX = 250                         # m
Y0_MIN = 50                          # m
TANK_VOLUME = 10                     # m^3
RETARDANT_DENSITY = 1050             # kg / m^3  
W_1 = 0.9                            # weight for droplets landing in fire range
W_2 = 0.1                            # weight for height of plane above ground

# --- Wind ---
WIND_X = 5.0                         # m/s
WIND_Y = 0.0                         # m/s
WIND_Z = 0.0                         # m/s
MU_F = 0.0000181                     # Viscosity of air, Pa * s = kg / (m * s)
RHO_A = 1.225                        # Density of air, kg / m^3

# --- Genetic Algorithm Parameters ---
K = 6                                # Strings generated by breeding
P = 6                                # Surviving strings for breeding
S = 20                               # Design strings per generation
G = 20                               # Total Generations
NUMLAM = 12
TOLERANCE = 0.01

# --- Airplane Constant ---
SPACING = 5.0                        # lateral nozzle spacing (m)

# Store the parameters in a dictionary
parameters_dict = {
    "GX": GX,
    "GY": GY,
    "GZ": GZ,
    "DT": DT,
    "STEPS": STEPS,
    "FRACTION_PARTICLES_TRACKED": FRACTION_PARTICLES_TRACKED,
    # Fire zone -- box
    "FIRE_X_MIN": FIRE_X_MIN,
    "FIRE_X_MAX": FIRE_X_MAX,
    "FIRE_Z_MIN": FIRE_Z_MIN,
    "FIRE_Z_MAX": FIRE_Z_MAX,
    # Fire zone -- shape selector and circle parameters
    "FIRE_ZONE_SHAPE": FIRE_ZONE_SHAPE,
    "FIRE_CENTER_X":   FIRE_CENTER_X,
    "FIRE_CENTER_Z":   FIRE_CENTER_Z,
    "FIRE_RADIUS":     FIRE_RADIUS,
    # Updraft
    "UPDRAFT_VELOCITY": UPDRAFT_VELOCITY,
    "UPDRAFT_DECAY":    UPDRAFT_DECAY,
    # Nozzle geometry
    "NOZZLE_AFT_OFFSET":  NOZZLE_AFT_OFFSET,
    "NOZZLE_DROP_OFFSET": NOZZLE_DROP_OFFSET,
    # Tank / retardant
    "TANK_VOLUME": TANK_VOLUME,
    "RETARDANT_DENSITY": RETARDANT_DENSITY,
    "Y0_MAX": Y0_MAX,
    "Y0_MIN": Y0_MIN,
    # Cost weights
    "W_1": W_1,
    "W_2": W_2,
    # Wind / fluid
    "WIND_X": WIND_X,
    "WIND_Y": WIND_Y,
    "WIND_Z": WIND_Z,
    "MU_F":  MU_F,
    "RHO_A": RHO_A,
    # GA
    "K": K,
    "P": P,
    "S": S,
    "G": G,
    "NUMLAM": NUMLAM,
    "TOLERANCE": TOLERANCE,
    # Airplane
    "SPACING": SPACING,
}

# Write the dictionary to a pickle file
with open('parameters.pkl', 'wb') as pkl_file:
    pickle.dump(parameters_dict, pkl_file)
